### ISSUE TITLE
Using getitems async

### ISSUE THREAD

**Issue by shptecheu** [vrslev/ikea-api-client#198]
@vrslev I debugged my issue from my previous request and it came down to calling `ikea_api.get_items` in an async manner.

Could I make a request to add to the documentation an example of this to avoid `RuntimeError: Event loop is closed`

**Comment by vrslev** [comment]
This kind of errors occur due to improper use of async and nothing to do with the library itself. In the previous issue you said you used Flask for your project, here's the documentation for Flask + async: https://flask.palletsprojects.com/en/3.0.x/async-await/.

The `ikea_api.get_items()` wrapper is async because a lot of asynchrony can happen there. For simple cases, I suggest you try ingka, pip and iows endpoints and see which one best suits your needs.

I also realised that `Ikea_api.get_items()` is quite complicated and useless for a wider audience (not saying I don't use it anymore 😅). Thinking of removing some wrappers now.
